server: 
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  zipkin:
    base-url: http://127.0.0.1:9411/