#server:
#  port: 9002
#
#spring:
#  application:
#    name: USER-SERVICE
<<<<<<< Updated upstream
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      default_schema: employee
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driverClassName: org.postgresql.Driver
      
=======
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#  datasource: 
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#  jpa:
#    properties:
#      hibernate: 
#        default_schema: public
#        dialect: org.hibernate.dialect.H2Dialect
#        ddl-auto: update
>>>>>>> Stashed changes
